# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joedralliam/Projects/Ocsfml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joedralliam/Projects/Ocsfml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joedralliam/Projects/Ocsfml/CMakeFiles /home/joedralliam/Projects/Ocsfml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joedralliam/Projects/Ocsfml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named audio

# Build rule for target.
audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audio
.PHONY : audio

# fast build rule for target.
audio/fast:
	$(MAKE) -f CMakeFiles/audio.dir/build.make CMakeFiles/audio.dir/build
.PHONY : audio/fast

#=============================================================================
# Target rules for targets named camlpp

# Build rule for target.
camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camlpp
.PHONY : camlpp

# fast build rule for target.
camlpp/fast:
	$(MAKE) -f CMakeFiles/camlpp.dir/build.make CMakeFiles/camlpp.dir/build
.PHONY : camlpp/fast

#=============================================================================
# Target rules for targets named clear

# Build rule for target.
clear: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clear
.PHONY : clear

# fast build rule for target.
clear/fast:
	$(MAKE) -f CMakeFiles/clear.dir/build.make CMakeFiles/clear.dir/build
.PHONY : clear/fast

#=============================================================================
# Target rules for targets named clock

# Build rule for target.
clock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clock
.PHONY : clock

# fast build rule for target.
clock/fast:
	$(MAKE) -f CMakeFiles/clock.dir/build.make CMakeFiles/clock.dir/build
.PHONY : clock/fast

#=============================================================================
# Target rules for targets named graphics

# Build rule for target.
graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics
.PHONY : graphics

# fast build rule for target.
graphics/fast:
	$(MAKE) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/build
.PHONY : graphics/fast

#=============================================================================
# Target rules for targets named infer

# Build rule for target.
infer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer
.PHONY : infer

# fast build rule for target.
infer/fast:
	$(MAKE) -f CMakeFiles/infer.dir/build.make CMakeFiles/infer.dir/build
.PHONY : infer/fast

#=============================================================================
# Target rules for targets named infer_audio

# Build rule for target.
infer_audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer_audio
.PHONY : infer_audio

# fast build rule for target.
infer_audio/fast:
	$(MAKE) -f CMakeFiles/infer_audio.dir/build.make CMakeFiles/infer_audio.dir/build
.PHONY : infer_audio/fast

#=============================================================================
# Target rules for targets named infer_graphics

# Build rule for target.
infer_graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer_graphics
.PHONY : infer_graphics

# fast build rule for target.
infer_graphics/fast:
	$(MAKE) -f CMakeFiles/infer_graphics.dir/build.make CMakeFiles/infer_graphics.dir/build
.PHONY : infer_graphics/fast

#=============================================================================
# Target rules for targets named infer_network

# Build rule for target.
infer_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer_network
.PHONY : infer_network

# fast build rule for target.
infer_network/fast:
	$(MAKE) -f CMakeFiles/infer_network.dir/build.make CMakeFiles/infer_network.dir/build
.PHONY : infer_network/fast

#=============================================================================
# Target rules for targets named infer_system

# Build rule for target.
infer_system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer_system
.PHONY : infer_system

# fast build rule for target.
infer_system/fast:
	$(MAKE) -f CMakeFiles/infer_system.dir/build.make CMakeFiles/infer_system.dir/build
.PHONY : infer_system/fast

#=============================================================================
# Target rules for targets named infer_window

# Build rule for target.
infer_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 infer_window
.PHONY : infer_window

# fast build rule for target.
infer_window/fast:
	$(MAKE) -f CMakeFiles/infer_window.dir/build.make CMakeFiles/infer_window.dir/build
.PHONY : infer_window/fast

#=============================================================================
# Target rules for targets named install_camlpp

# Build rule for target.
install_camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 install_camlpp
.PHONY : install_camlpp

# fast build rule for target.
install_camlpp/fast:
	$(MAKE) -f CMakeFiles/install_camlpp.dir/build.make CMakeFiles/install_camlpp.dir/build
.PHONY : install_camlpp/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f CMakeFiles/network.dir/build.make CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named pong

# Build rule for target.
pong: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pong
.PHONY : pong

# fast build rule for target.
pong/fast:
	$(MAKE) -f CMakeFiles/pong.dir/build.make CMakeFiles/pong.dir/build
.PHONY : pong/fast

#=============================================================================
# Target rules for targets named system

# Build rule for target.
system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system
.PHONY : system

# fast build rule for target.
system/fast:
	$(MAKE) -f CMakeFiles/system.dir/build.make CMakeFiles/system.dir/build
.PHONY : system/fast

#=============================================================================
# Target rules for targets named uninstall_camlpp

# Build rule for target.
uninstall_camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall_camlpp
.PHONY : uninstall_camlpp

# fast build rule for target.
uninstall_camlpp/fast:
	$(MAKE) -f CMakeFiles/uninstall_camlpp.dir/build.make CMakeFiles/uninstall_camlpp.dir/build
.PHONY : uninstall_camlpp/fast

#=============================================================================
# Target rules for targets named window

# Build rule for target.
window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 window
.PHONY : window

# fast build rule for target.
window/fast:
	$(MAKE) -f CMakeFiles/window.dir/build.make CMakeFiles/window.dir/build
.PHONY : window/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... audio"
	@echo "... camlpp"
	@echo "... clear"
	@echo "... clock"
	@echo "... edit_cache"
	@echo "... graphics"
	@echo "... infer"
	@echo "... infer_audio"
	@echo "... infer_graphics"
	@echo "... infer_network"
	@echo "... infer_system"
	@echo "... infer_window"
	@echo "... install_camlpp"
	@echo "... network"
	@echo "... pong"
	@echo "... rebuild_cache"
	@echo "... system"
	@echo "... uninstall_camlpp"
	@echo "... window"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

