# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Projects\Ocsfml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Projects\Ocsfml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\Ocsfml\CMakeFiles D:\Projects\Ocsfml\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\Ocsfml\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named audio

# Build rule for target.
audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) audio
.PHONY : audio

# fast build rule for target.
audio\fast:
	$(MAKE) -f CMakeFiles\audio.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\audio.dir\build
.PHONY : audio\fast

#=============================================================================
# Target rules for targets named camlpp

# Build rule for target.
camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) camlpp
.PHONY : camlpp

# fast build rule for target.
camlpp\fast:
	$(MAKE) -f CMakeFiles\camlpp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\camlpp.dir\build
.PHONY : camlpp\fast

#=============================================================================
# Target rules for targets named clear

# Build rule for target.
clear: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clear
.PHONY : clear

# fast build rule for target.
clear\fast:
	$(MAKE) -f CMakeFiles\clear.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\clear.dir\build
.PHONY : clear\fast

#=============================================================================
# Target rules for targets named clock

# Build rule for target.
clock: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clock
.PHONY : clock

# fast build rule for target.
clock\fast:
	$(MAKE) -f CMakeFiles\clock.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\clock.dir\build
.PHONY : clock\fast

#=============================================================================
# Target rules for targets named graphics

# Build rule for target.
graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) graphics
.PHONY : graphics

# fast build rule for target.
graphics\fast:
	$(MAKE) -f CMakeFiles\graphics.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\graphics.dir\build
.PHONY : graphics\fast

#=============================================================================
# Target rules for targets named infer

# Build rule for target.
infer: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer
.PHONY : infer

# fast build rule for target.
infer\fast:
	$(MAKE) -f CMakeFiles\infer.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer.dir\build
.PHONY : infer\fast

#=============================================================================
# Target rules for targets named infer_audio

# Build rule for target.
infer_audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer_audio
.PHONY : infer_audio

# fast build rule for target.
infer_audio\fast:
	$(MAKE) -f CMakeFiles\infer_audio.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer_audio.dir\build
.PHONY : infer_audio\fast

#=============================================================================
# Target rules for targets named infer_graphics

# Build rule for target.
infer_graphics: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer_graphics
.PHONY : infer_graphics

# fast build rule for target.
infer_graphics\fast:
	$(MAKE) -f CMakeFiles\infer_graphics.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer_graphics.dir\build
.PHONY : infer_graphics\fast

#=============================================================================
# Target rules for targets named infer_network

# Build rule for target.
infer_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer_network
.PHONY : infer_network

# fast build rule for target.
infer_network\fast:
	$(MAKE) -f CMakeFiles\infer_network.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer_network.dir\build
.PHONY : infer_network\fast

#=============================================================================
# Target rules for targets named infer_system

# Build rule for target.
infer_system: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer_system
.PHONY : infer_system

# fast build rule for target.
infer_system\fast:
	$(MAKE) -f CMakeFiles\infer_system.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer_system.dir\build
.PHONY : infer_system\fast

#=============================================================================
# Target rules for targets named infer_window

# Build rule for target.
infer_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) infer_window
.PHONY : infer_window

# fast build rule for target.
infer_window\fast:
	$(MAKE) -f CMakeFiles\infer_window.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\infer_window.dir\build
.PHONY : infer_window\fast

#=============================================================================
# Target rules for targets named install_camlpp

# Build rule for target.
install_camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) install_camlpp
.PHONY : install_camlpp

# fast build rule for target.
install_camlpp\fast:
	$(MAKE) -f CMakeFiles\install_camlpp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\install_camlpp.dir\build
.PHONY : install_camlpp\fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) network
.PHONY : network

# fast build rule for target.
network\fast:
	$(MAKE) -f CMakeFiles\network.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\network.dir\build
.PHONY : network\fast

#=============================================================================
# Target rules for targets named pong

# Build rule for target.
pong: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) pong
.PHONY : pong

# fast build rule for target.
pong\fast:
	$(MAKE) -f CMakeFiles\pong.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\pong.dir\build
.PHONY : pong\fast

#=============================================================================
# Target rules for targets named system

# Build rule for target.
system: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) system
.PHONY : system

# fast build rule for target.
system\fast:
	$(MAKE) -f CMakeFiles\system.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\system.dir\build
.PHONY : system\fast

#=============================================================================
# Target rules for targets named uninstall_camlpp

# Build rule for target.
uninstall_camlpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) uninstall_camlpp
.PHONY : uninstall_camlpp

# fast build rule for target.
uninstall_camlpp\fast:
	$(MAKE) -f CMakeFiles\uninstall_camlpp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\uninstall_camlpp.dir\build
.PHONY : uninstall_camlpp\fast

#=============================================================================
# Target rules for targets named window

# Build rule for target.
window: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) window
.PHONY : window

# fast build rule for target.
window\fast:
	$(MAKE) -f CMakeFiles\window.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\window.dir\build
.PHONY : window\fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... audio
	@echo ... camlpp
	@echo ... clear
	@echo ... clock
	@echo ... edit_cache
	@echo ... graphics
	@echo ... infer
	@echo ... infer_audio
	@echo ... infer_graphics
	@echo ... infer_network
	@echo ... infer_system
	@echo ... infer_window
	@echo ... install_camlpp
	@echo ... network
	@echo ... pong
	@echo ... rebuild_cache
	@echo ... system
	@echo ... uninstall_camlpp
	@echo ... window
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

